[server]
address = "127.0.0.1:8888"
database_url = "postgres://freyja-moth@localhost/audio"
default_mime = "text/ron"

[content_rules.audio]
allowed_mimes = [ "audio/mpeg" ]

[content_rules.script]
allowed_mimes = [ "text/markdown" ]
