[server]
address = "127.0.0.1:8888"
database_url = "postgres://freyja-moth@localhost/audio"
default_mime = "text/ron"

[content.script]
allowed_mimes = [ "application/json" ]

[content.audio]
allowed_mimes = [ "audio/mpeg" ]

[content.script]
allowed_mimes = [ "text/markdown" ]
